---
- hosts: localhost
  connection: local
  collections:
    - infoblox.b1ddi_modules

  vars:
  - host: "{{ Host server to connect to }}"
  - api: "{{ api key to access the server }}"

  tasks:
    #  Gather information of with multiple filters
    - name: Gather the tags  of an for a given IPSpace name
      b1_a_record_gather:
        host: "{{ host }}"
        api_key: "{{ api }}"
        state: gather
          #fields: [ 'id', 'tags', 'comment']
          #filters: {"address": "30.0.0.18", "name": "test-a-record1"}
      register: a_rec_lists
    - debug: msg="{{ a_rec_lists }}"



