---
- hosts: localhost
  connection: local
  collections:
    - infoblox.b1ddi_modules

  vars:
  - host: "{{ Host server to connect to }}"
  - api: "{{ api key to access the server }}"

  tasks:
    - name: Gather cname
      b1_cname_record_gather:
        host: "{{ host }}"
        api_key: "{{ api }}"
        state: gather
          #fields: [ 'id', 'comment', 'tags']
        filters: {"cname": "test-b-record1.qa-zone-1.", "name": "test-cname-record1"}
      register: cname_rec_lists
    - debug: msg="{{ cname_rec_lists }}"

