---
- hosts: localhost
  connection: local
  collections:
    - infoblox.b1ddi_modules

  vars:
  - host: "{{ host_server }}"
  - api: "{{ api_key }}"

  tasks:
    #  Create a ipv4 reserved address in a given IP space
    - name: Create ipv4 reserved address in a given IP Space
      b1_ipam_ipv4_reservation:
        space: "Test-Ansible-Space"
        address: '172.16.0.18'
        name: "Test-Address-18"
        comment: "This is the test address "
        tags:
          - "Org": "Infoblox"
        api_key: "{{ api }}"
        host: "{{ host }}"
        state: present

    #  Update the ipv4 reserved address in a given IP space
    - name: Update ipv4 reserved address in a given IP Space
      b1_ipam_ipv4_reservation:
        space: "Test-Ansible-Space"
        address: '{"new_address": "172.16.0.15", "old_address": "172.16.0.18"}'
        name: "Test-Ansible-address_15"
        comment: "This is the test address-mod"
        api_key: "{{ api }}"
        host: "{{ host }}"
        state: present

    #  Create a ipv4 reservation in a given IP space using next_available_address_block
    - name: Create reserved address using next-available subnet
      b1_ipam_ipv4_reservation:
        space: "Test-Ansible-Space"
        address: '{"next_available_ip": {"subnet": "172.16.0.0/24"}}'
        name: "Test-Ansible-AB_nextAvailable-reservedIP"
        comment: "This is the test reserved ip using nextavailable"
        api_key: "{{ api }}"
        host: "{{ host }}"
        state: present

    #  Delete an existing Reservation
    - name: Delete ipv4 reservation address.
      b1_ipam_ipv4_reservation:
        address: "172.16.0.4"
        space: "Test-Ansible-Space"
        api_key: "{{ api }}"
        host: "{{ host }}"
        state: absent

