---
- hosts: localhost
  connection: local
  collections:
    - infoblox.b1ddi_modules

  vars:
  - host: "{{ Host server to connect to }}"
  - api: "{{ api key to access the server }}"
  tasks:
    - name: GET all DNS View
      b1_dns_view:
        api_key: "{{ api }}"
        host: "{{ host }}"
        state: get

    - name: GET Specific DNS View
      b1_dns_view:
        name: "Test-View"
        api_key: "{{ api }}"
        host: "{{ host }}"
        state: get

    - name: Create DNS View
      b1_dns_view:
        name: "Test-View"
        tags:
          - Test: Value
        comment: "This is playbook"
        api_key: "{{ api }}"
        host: "{{ host }}"
        state: present

    - name: Update DNS View 
      b1_dns_view:
         name: '{"new_name": "Test-View2", "old_name": "Test-View"}'
         tags:
           - Test: "Value1"
         comment: "This is an update"
         api_key: "{{ api }}"
         host: "{{ host }}"
         state: present

    - name: Delete DNS View
      b1_dns_view:
         name: "Test-View2"
         api_key: "{{ api }}"
         host: "{{ host }}"
         state: absent
